### ISSUE TITLE
URL Bar with multiple tabs is very small

### ISSUE THREAD

**Issue by Kshitij841** [Cookie755233/firefox-minimal#1]
When opening multiple tabs, I had around 15, the URL Bar becomes very small (along with multiple other nav bar elements), maybe a way to lower the area allocated to browse through tabs can be decreased and a min-width of URL is added for it to not become that short.

Could there be anyway to remove the borders surrounding the website window or reduce them by a lot? It seems great as to looking great with adaptive tab bar colours but feels like a bit of wastage of space.

I don't mind missing of windows control buttons (minimize, maximize and close), you gave a bit of space to move around firefox window is great, the only caveat is with windows snap feature and powertoys, the maximize button is also used snapping multiple applications to different window areas, I kind of miss that as I like to open a word doc with the browser, maybe adding something to accomodate that or maybe I missed something.

**Comment by Cookie755233** [comment]
Hi, I don't see the problem you mentioned. Can you provide any screenshot? 
As far as my concern, the urlbar element does not at all change its size. Only the tabs become smaller until a certain points the arrow before/after tabs will appear.
<img width="1722" alt="image" src="https://github.com/Cookie755233/firefox-minimal/assets/85786140/ff3e962c-5d8d-4e07-91c3-c03bbb0d1092">

**Comment by Kshitij841** [comment]
Hi, sorry about that, should have attached the screenshot earlier.
![image](https://github.com/Cookie755233/firefox-minimal/assets/75718745/d4a9dffc-be84-4b1f-8f15-6916f306ca48)

I suspect it is because of my clutter with toolbar elements like zoom, private tab and other things.

EDIT: As I am using Adaptive Color Tab extension and when there's a bit of lighter color chosen from the website, the URL becomes incomprehensible. Ex:
![Screenshot 2024-03-14 115353](https://github.com/Cookie755233/firefox-minimal/assets/75718745/16eeac2f-9781-4c6e-b8d7-ecba619af223)


EDIT #2: Fixed the Adaptive Color Tab problem by removing the following code:
```
/* Change URL Bar background color */
@media (prefers-color-scheme: dark) {
  #urlbar-background {
    background-color: #2a2a2a !important;
  }
}

@media (prefers-color-scheme: light) {
  #urlbar-background {
    background-color: #d6d6d6 !important;
  }
}

@media (prefers-color-scheme: dark) {
  #urlbar-results > *[selected=""] {
    background-color: #424242 !important;
  }
}

@media (prefers-color-scheme: light) {
  #urlbar-results > *[selected=""] {
    background-color: #e8e8e8 !important;
  }
}
```
Pretty simple 'fix'.

For the URL bar being small, I just removed the extra things that cluttered these things like zoom element, pvt. session thingy.

One last thing for any other users out here who want the windows control buttons like me, remove the following code:
```
/* Remove close window button*/
.titlebar-buttonbox-container {
  display: none !important;
}
```

For reducing 'website window' border, you can use the following code:
```
@media (prefers-color-scheme: dark) {
  #main-window:not([sizemode="fullscreen"]) #appcontent browser {
    border-radius: 5px !important;
    margin: 5px 5px 5px 5px !important;
    border: 1.5px solid rgba(0, 0, 0, 0);
    transition: border 0.3s ease;
    box-shadow: 0 0 10px 5px rgba(0, 0, 0, 0.5);
    clip-path: circle(80%) !important;
  }

  #main-window:not([sizemode="fullscreen"]) #appcontent browser:hover {
    border: 1.5px solid rgba(204, 204, 204, 0.6);
    box-shadow: 0 0 10px 5px rgba(0, 0, 0, 0.5);
  }
}

@media (prefers-color-scheme: light) {
  #main-window:not([sizemode="fullscreen"]) #appcontent browser {
    border-radius: 5px !important;
    margin: 5px 5px 5px 5px !important;
    border: 1.5px solid rgba(51, 51, 51, 0.1);
    transition: border 0.3s ease;
    box-shadow: 0 0 10px 5px rgba(255, 255, 255, 0.5);
    clip-path: circle(80%) !important;
  }

  #main-window:not([sizemode="fullscreen"]) #appcontent browser:hover {
    border: 1.5px solid rgba(51, 51, 51, 0.6);
    box-shadow: 0 0 10px 5px rgba(255, 255, 255, 0.5);
  }
}
```
OR remove this code entirely to go borderless.

Great theme! Just customized more according to my liking.

**Comment by Cookie755233** [comment]
You actually solved yourself while Im debugging. 🤣 
The decreased boarder is a great touch! I'm reducing border-radius to my taste too. Appreciated!
